# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_service.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image_service.proto\x12\x05image\"\"\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\x1f\n\rImageResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2I\n\x0cImageService\x12\x39\n\x0cProcessImage\x12\x13.image.ImageRequest\x1a\x14.image.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=30
  _globals['_IMAGEREQUEST']._serialized_end=64
  _globals['_IMAGERESPONSE']._serialized_start=66
  _globals['_IMAGERESPONSE']._serialized_end=97
  _globals['_IMAGESERVICE']._serialized_start=99
  _globals['_IMAGESERVICE']._serialized_end=172
# @@protoc_insertion_point(module_scope)
